### ISSUE TITLE
Implement multiple locations per access area request

### ISSUE THREAD

**Issue by nilsnolde** [nilsnolde/ORStools#12]
Pros:
- less server load
- response includes overlapping areas, if flag is set

**Comment by nilsnolde** [comment]
@TimMcCauley, please revert when you added support for more than 2 locations per request. On hold until then.

**Comment by TimMcCauley** [comment]
@nilsnolde, we have added support for 5 locations now.

**Comment by nilsnolde** [comment]
Fixed in [new branch] (https://github.com/nilsnolde/ORStools/tree/OSMtools_v0.3.1_AccGroups)

At QGIS dev community for approval!
