### ISSUE TITLE
embed plugin window in the main window on the left side

### ISSUE THREAD

**Issue by karussell** [nilsnolde/ORStools#21]
This would avoid frequent searches where to open the plugin if the plugin is always open and cannot be (easily) closed :)

**Comment by nilsnolde** [comment]
I tried it for a few hours, but wasn´t really successful. It´s fairly tiresome to interact with QGIS dock widgets, that´d have taken a serious deep dive with unsure outcome. Sorry...

**Comment by karussell** [comment]
ok, still thanks :+1: !
