### ISSUE TITLE
ValueError: could not convert string to float: Long

### ISSUE THREAD

**Issue by tkan** [nilsnolde/ORStools#23]
Fresh OSM Tools install on Ubuntu 16.04, QGIS 2.14.11. Got an API key from the website, pasted, clicked "OK" in the main window and this crash happens.

![screenshot from 2017-06-26 09-37-05](https://user-images.githubusercontent.com/1358178/27529138-9edc9d46-5a53-11e7-9777-fc062e029031.png)

**Comment by nilsnolde** [comment]
This line takes the start location from the 'Map Now' button and splits the X, Y from the label on the side into coordinates. So, make sure, the 'Map Now' button actually printed coordinates right next to it.

Also, don´t have more than 1 window open of OSM tools. They can interfere weirdly. It´s not perfect.

If the request still doesn´t work, please elaborate on the steps you take to get there.

**Comment by tkan** [comment]
Thanks for the feedback but this more of a 'just wanted to let you know thing'. The plugin is working fine for me. It is just an awkward feeling to play around with the plugin and get an error within 10 seconds. I guess a 'try' and 'except' (+ maybe feedback in the QGIS message bar) would be enough to fix this.

**Comment by nilsnolde** [comment]
Ok, I´ll keep it in mind for the next release.
