### ISSUE TITLE
Multiple runs Issue: ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by imcebean** [nilsnolde/ORStools#25]
I am trying to determine the accessibility isochrones of several points in QGIS, either at the same time or one at a time, but every time I try and do this, I get the following error:
Traceback (most recent call last):
			  File "/Users/[username]/.qgis2/python/plugins/OSMtools/osm_tools_access.py", line 91, in valueChanged
			    self.iso_amount = ceil(self.dlg.iso_max.value()/self.dlg.iso_int.value())
			ZeroDivisionError: float division by zero

I am able to use OSM tools to determine the isochrones of points, but only if I close out of my map and reopen it after each point. Is there a way to analyse multiple points more efficiently without having to reopen the programme after each run?

**Comment by nilsnolde** [comment]
Hi,

can you please post a screenshot of your parameters? When do you get this error? After it successfully calculated your isochrones?

The error is telling you that your 'Interval' parameter is apparently 0. This calculation is done every time you change the value of one of the four parameters in the GUI. That´s the only way I can reproduce your error. For me, this sounds like a user error, not an inherent program fault.

BTW, you can also reload plugins with [Plugin Reloader](https://plugins.qgis.org/plugins/plugin_reloader/)

**Comment by nilsnolde** [comment]
No answer, will close.
