### ISSUE TITLE
Visualising isochrones layers from result

### ISSUE THREAD

**Issue by mobcdi** [nilsnolde/ORStools#26]
Hi Nils,
Thanks for developing the tool. Is it possible for you to outline how to format the resulting .shp file which gives the distance to end up with distinct banding. I've tried adding in columns by concatenating the integer value with another field to create a label for the band but I'm not sure if its the best way and if it can then be used to intersect with other point layers

**Comment by nilsnolde** [comment]
Hi, 

I needed a few reads over this, but now I know what you were after:) You actually made me realize a glitch in the code. When using layers for isochrones, it puts 'string' as the 'AA_MINS' column type, while it should be 'int'. I´ll fix for the next version. So, you can build your graduated style directly on the AA_MINS column.

out of curiosity: why the dissolve? You actually don´t dissolve anything when you use feature unique ID´s, the output will be the exact same as the input.

**Comment by mobcdi** [comment]
i thought I needed the dissolve to create the shapes correctly but thats coming from a novice, glad I was able to find a bug, will I get notification in qgis when the update is available?

**Comment by nilsnolde** [comment]
I´m actually unsure about that. You´ll be able to upgrade manually in the plugin manager once it´s available. You can also check the 'Check for updates on startup' option:
![image](https://user-images.githubusercontent.com/25637358/28530053-c0421ae2-7092-11e7-8e9e-4b1b7fe7f7ea.png)

**Comment by nilsnolde** [comment]
The new version 0.3.1 fixed the issue of 'AA_MINS' and 'AA_METERS' having type 'int' instead of 'string'.
