### ISSUE TITLE
Corrupt Extension

### ISSUE THREAD

**Issue by NolJuL** [nilsnolde/ORStools#36]
When I want to install the extension, the following message appears : "No module named shapely.geometry"

**Comment by nilsnolde** [comment]
Hi @NolJuL, sorry, was away on vacation for a longer time.. 

Few questions:
* When you open the Python console in QGIS (Menu > Plugins > Python Console) and type `import shapely` and or `from shapely import geometry`, what does it say? In case there´s no error message at this point, I´m clueless. If there is one, reinstall v2.18.14
* When exactly does the error appear? It should install correctly regardless. However, when you try to start it, it could crash with the error you´re describing if the installation misses shapely for some reason
* What QGIS version are you using? This sounds like a corrupt QGIS installation... Try reinstall, preferably the most recent

Cheers
Nils

**Comment by NolJuL** [comment]
Hi @nilsnolde ,
Thanks for your answer. The problem exists in Qgis installed with Osgeo, not in Qgis "alone".
The error appears when i click on "install extension"

Thanks
Nol

**Comment by nilsnolde** [comment]
ok @NolJuL, I´m not exactly sure what you mean. OSgeo is an inherent part of any QGIS installation.

Can you update me on the rest please? Did you try re-installing the latest version? Did you try to type the commands I asked you for in the QGIS Python console? Alternatively you can also start Python in the OSgeo console and type the commands there, same thing.
