### ISSUE TITLE
intervals are not part of the attributes list

### ISSUE THREAD

**Issue by riccardoklinger** [nilsnolde/ORStools#5]
Hi Nils,

first: great job! Unfortunately your isochrone analysis does not reflect intervals in the polygon layer. I would assume to see a polygon for each intervall. At the moment it is just one single polygon.
![grafik](https://cloud.githubusercontent.com/assets/7377897/25802616/5908f3a4-33f3-11e7-8ff9-c2cd0f0336f9.png)

**Comment by nilsnolde** [comment]
Ah damn, I actually fixed that! It works if you leave the default isochrone and interval though;) It´s a tiny bug in the change textbox event.

I´ll fix and revert.

Thanks for the quick reporting mate!

**Comment by nilsnolde** [comment]
Sorry, can´t reproduce.. To be sure I downloaded the version directly from the Plugin directory, it´s fine on my side:
![image](https://cloud.githubusercontent.com/assets/25637358/25826482/4f283fd0-3447-11e7-9d39-f1d60dc46f91.png)

You´re sure you´re not using a deprecated version from GitHub? It´s only up-to-date in the trunk, not in the branch. 

Can you plz look into the 'osm_tools_access.py': on line 83, it should say

`    def valueChanged(self):
        self.iso_max = self.dlg.iso_max.value() * 60
        self.iso_int = self.dlg.iso_int.value() * 60`

**Comment by nilsnolde** [comment]
Sorry, it should say:
```
    def valueChanged(self):
        self.iso_max = self.dlg.iso_max.value() * 60
        self.iso_int = self.dlg.iso_int.value() * 60
```

**Comment by nilsnolde** [comment]
Closing this, assuming it was a random error.
