### ISSUE TITLE
OSM Tools window to big

### ISSUE THREAD

**Issue by hoge6b01** [nilsnolde/ORStools#9]
Dear Nils,

when using the tools on my Mint Laptop 13" 1366x768 the tool's window is to large to see the lower part of it. Therefore the routing cannot be started. Unfortunately the windows isn't resizable. Any idea?
![image](https://cloud.githubusercontent.com/assets/5871910/26076476/2bdb0860-39b9-11e7-98e7-b08dd8a85645.png)

**Comment by nilsnolde** [comment]
Oops, good point. I´ll make it resizable until the end of the week.

As a workaround, if you press 'Tab' to switch through UI elements, the 'OK' button will be highlighted after the 'Map' via button and/or after the 'Clear' via button. That should at least get you started for now. Reminds me, I have to set the 'Tab' order right, too...

Good luck
Nils

**Comment by nilsnolde** [comment]
Hi,

fixed in [new branch](https://github.com/nilsnolde/ORStools/tree/osm_tools_v0.2_GUIscrollbar_Nodi).

I didn´t really make it smart enough to adjust to low resolution small screens, but the size should be generally small enough now. 

Please test and revert.

**Comment by hoge6b01** [comment]
Thanks. That works!
